#!/bin/bash
# $Id: vzpkgadd,v 1.5 2006/05/11 14:23:39 kir Exp $
# Copyright (C) 2005, SWsoft. Licensed under GNU GPL v.2.
#
# Simple wrapper for vzrpm -U

# Handle options
case $1 in
	-f|--force)
		OPTS="--force --nodeps"
		shift
		;;
esac

VEID=$1
shift
exec /usr/bin/vzrpm $VEID $OPTS -U $*
