#!/bin/bash
# $Id: vzyum,v 1.13 2006/05/11 14:38:18 kir Exp $
#
# vzyum - a wrapper for yum to use yum for OpenVZ VE.
#
# Copyright (C) 2005, 2006, SWsoft. Licensed under GNU GPL v.2.
# By Kir Kolyshkin.

TOOLDIR=/usr/share/vzpkg
#DEBUG_LEVEL=4

. ${TOOLDIR}/functions

log4 Started $0 $*

set -e

function usage() {
	cat << USAGE_EOF 1>&2
Usage: $PROGNAME <VEID> <arguments>
  where <arguments> are yum arguments.
USAGE_EOF
	exit $1
}

if test $# -lt 2; then
        log2 "Wrong number of parameters specified"
        usage
fi

get_veid $1
shift
USER_ARGS=$*
# Sanity checks
STATUS=`$VZCTL status $VEID` || abort "Can't get status for VE $VEID: " \
	"vzctl status failed with code $?"
echo $STATUS | grep -qw "exist" || abort "VE $VEID not exist!"
echo $STATUS | grep -qw "running" || abort "VE $VEID not running; " \
	"you should start it first"
get_ve_os_template $VEID || abort "Can't get OSTEMPLATE for VE $VEID"
TEMPLATE=`get_vz_var TEMPLATE`
OST=`ost2full $OSTEMPLATE` || abort "No such OS template: $OSTEMPLATE"
set $OST
OSNAME=$1
OSVER=$2
OSSET=$3
OSARCH=$4
TDIR=$5
check_ost_exists $OSNAME $OSVER $OSSET $OSARCH || exit 1
MARK64=`is_64bit $OSARCH`
YUM_ARGS=`yum_conf $TDIR`
YUM_ARGS="$YUM_ARGS --installroot $VE_ROOT --vps=$VEID"
# Set PYTHONPATH
PYTHONPATH=`get_rpm_pythonhome $TDIR`
export PYTHONPATH
log4 PYTHONPATH=$PYTHONPATH
# Set LD_LIBRARY_PATH to access rpm libs
set +u
LD_LIBRARY_PATH=`get_rpmlib_path $TDIR`:$LD_LIBRARY_PATH
set -u
export LD_LIBRARY_PATH
log4 LD_LIBRARY_PATH=$LD_LIBRARY_PATH
log3 exec $YUM $YUM_ARGS $USER_ARGS
exec $YUM $YUM_ARGS $USER_ARGS
