.TH vzrpm 8 "May 11, 2006" "OpenVZ" "Virtual Environments"
.SH NAME
vzrpm \- rpm wrapper for use with OpenVZ's VE
.SH SYNOPSIS
\fBvzrpm\fR \fIVEID\fR \fIrpmoption\fR [...]
.SH DESCRIPTION
This is a simple \fBrpm\fR(\fI8\fR) wrapper, which makes it easy to use
\fBrpm\fR(\fI8\fR) for a given VE from the OpenVZ host system.
Use it like ordinary \fBrpm\fR(\fI8\fR), just give a \fIVEID\fR as
a first argument.
.SH EXAMPLES
\fB\f(CWvzrpm 123 -qa\fR
.PP
\fB\f(CWvzrpm 123 -ihv package-1.0-1.i386.rpm\fR
.SH SEE ALSO
.BI vzyum (8)\fR.
.SH COPYRIGHT
Copyright (C) 2005, 2006, SWsoft. Distributed under GNU GPL.
.SH AUTHOR
Kir Kolyshkin <kir@openvz.org>
