.TH vzyum 8 "May 11, 2006" "OpenVZ" "Virtual Environments"
.SH NAME
vzyum \- yum wrapper for use with OpenVZ's VE
.SH SYNOPSIS
\fBvzyum\fR \fIVEID\fR \fIyumoption\fR [...]
.SH DESCRIPTION
This is a simple \fByum\fR(\fI8\fR) wrapper, which makes it easy to use
\fByum\fR(\fI8\fR) from the OpenVZ host system command line. Use it
like ordinary \fByum\fR(\fI8\fR), just give VE ID as the first argument.
.PP
The main point of using \fBvzyum\fR instead of yum is in this case yum cache
is shared between VEs, so you don't have to download a package update
100 times if you have 100 VEs based on the same OS template.
.SH EXAMPLES
\fB\f(CWvzyum 123 update\fR
.PP
\fB\f(CWvzyum 123 install mysql\fR
.PP
\fB\f(CWvzyum 123 -d10 check-update\fR
.SH SEE ALSO
.BI vzpkgcache (8)\fR,
.BI vzctl (8)\fR,
.BI yum (8)\fR.
.SH COPYRIGHT
Copyright (C) 2005, 2006, SWsoft. Distributed under GNU GPL.
.SH AUTHOR
Kir Kolyshkin <kir@openvz.org>
